

name : plu-mapping

on: [push]

env:
  TEMPLATE-FILE: iac
  PARAMTER-FILE: parameters/azuredeploy.json
  RESOURCE-GROUP: test-rg
  LOCATION: westeurope
  SUBSCRIPTION-ID: c9490d92-aa64-4485-b2b3-6ab98110f1a0
  
jobs:
  deploy-cr: 
    runs-on : ubuntu-latest

    steps: 
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.9
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: ../../acr.bicep
          failOnStdErr: false   
