
name : plu-mapping

on: [push]

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name : Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name : build 
        run: dotnet build 
      - name : publish
        run :  dotnet publish Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/pluapi
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
         name: .net-app
         path: ${{env.DOTNET_ROOT}}/pluapi
  deploy: 
    runs-on : ubuntu-latest
     steps: 
      - name : AzureAppServieDeploy
        uses 
        
      
