
name : plu-mapping

on: [push]

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name : Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name : build 
        run: dotnet build 
      - name : publish
        run :  dotnet publish Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/pluapi
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
         name: .net-app
         path: ${{env.DOTNET_ROOT}}/pluapi
  deploy: 
    runs-on : ubuntu-latest
    needs: buildandtest
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: .net-app
          path: .net-app
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.6
        with:
          # Name of the Azure Web App
          app-name: devops-test-enabler
          # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
          package: .net-app
          resource-group-name: magnar-rg
      
